spring:
  profiles:
    active: smart

  thymeleaf:
    cache: false

  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
  jpa:
    open-in-view: false
hr:
  limits:
    1: 1
    2.5: 2
    5: 5
    10: 10


  normal: 5
server:
  error:
    include-message: always




